version: '3'

services:
  app:
    container_name: habi_container
    build: ./
    volumes:
      - ./app:/code/app
    ports:
      - 8000:80
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 80
    env_file:
      - .env